import type { HouseNavLevel } from './types';

export const anaokuluLevels: HouseNavLevel[] = [
  {
    id: 'okul-1',
    order: 1,
    title: 'Banyoya Git',
    instructions: 'Komutları kullanarak karakteri Banyo kapısına götür.',
    mapRoomId: 'main',
    startAtObjectId: 'door-child-room',
    taskSteps: [
      { kind: 'moveTo', targetObjectId: 'door-bathroom', actionLabel: 'Banyo kapısına git', feedbackLabel: 'Banyoya ulaştın!' },
    ],
    points: 10,
    optimalDurationSeconds: 30,
    minSteps: 3,
  },
  {
    id: 'okul-2',
    order: 2,
    title: 'Elini Yüzünü Yıka',
    instructions: 'Lavaboya git ve elini yüzünü yıka.',
    mapRoomId: 'bathroom',
    taskSteps: [
      {
        kind: 'miniPuzzle',
        targetObjectId: 'sink',
        actionLabel: 'Ellerini yıkamadan önce sırayı bul',
        feedbackLabel: 'Doğru sırayla yıkadın!',
        puzzleType: 'orderedChoice',
      },
      { kind: 'enterAt', targetObjectId: 'sink', actionLabel: 'Elini yüzünü yıka', feedbackLabel: 'Elini yüzünü yıkadın!' },
    ],
    points: 20,
    optimalDurationSeconds: 50,
    minSteps: 3,
  },
  {
    id: 'okul-3',
    order: 3,
    title: 'Mutfağa Git',
    instructions: 'Komutları kullanarak karakteri Mutfak kapısına götür.',
    mapRoomId: 'main',
    startAtObjectId: 'door-bathroom',
    taskSteps: [
      { kind: 'moveTo', targetObjectId: 'door-kitchen', actionLabel: 'Mutfak kapısına git', feedbackLabel: 'Mutfağa ulaştın!' },
    ],
    points: 10,
    optimalDurationSeconds: 30,
    minSteps: 3,
  },
  {
    id: 'okul-4',
    order: 4,
    title: 'Kahvaltı Yap',
    instructions: 'Masanın yanına git ve kahvaltı yap.',
    mapRoomId: 'kitchen',
    taskSteps: [
      { kind: 'enterAt', targetObjectId: 'table', actionLabel: 'Kahvaltı yap', feedbackLabel: 'Kahvaltı yaptın!' },
    ],
    points: 15,
    optimalDurationSeconds: 35,
    minSteps: 2,
  },
  {
    id: 'okul-5',
    order: 5,
    title: 'Çocuk Odasına Git',
    instructions: 'Komutları kullanarak karakteri Çocuk Odası kapısına götür.',
    mapRoomId: 'main',
    startAtObjectId: 'door-kitchen',
    taskSteps: [
      { kind: 'moveTo', targetObjectId: 'door-child-room', actionLabel: 'Çocuk Odası kapısına git', feedbackLabel: 'Çocuk odasına ulaştın!' },
    ],
    points: 10,
    optimalDurationSeconds: 30,
    minSteps: 3,
  },
  {
    id: 'okul-6',
    order: 6,
    title: 'Çantanı Hazırla',
    instructions: 'Önce kitabı al, sonra çantaya git ve kitabı çantaya koy. Sıra önemli!',
    mapRoomId: 'child-room',
    taskSteps: [
      { kind: 'miniPuzzle', targetObjectId: 'wardrobe', actionLabel: 'Kıyafetlerini giy', feedbackLabel: 'Kıyafetlerini giydin!', puzzleType: 'orderedChoice' },
      { kind: 'enterAt', targetObjectId: 'book', actionLabel: 'Kitabı al', feedbackLabel: 'Kitabı aldın!' },
      { kind: 'enterAt', targetObjectId: 'backpack', actionLabel: 'Çantayı bul', feedbackLabel: 'Çantayı buldun!' },
      { kind: 'enterAt', targetObjectId: 'backpack', actionLabel: 'Kitabı çantaya koy', feedbackLabel: 'Kitabı çantaya koydun!' },
    ],
    points: 25,
    optimalDurationSeconds: 90,
    minSteps: 6,
  },
  {
    id: 'okul-7',
    order: 7,
    title: 'Evden Çık',
    instructions: 'Çıkış kapısına git, önce bulmacayı çöz sonra evden çık.',
    mapRoomId: 'main',
    startAtObjectId: 'door-child-room',
    taskSteps: [
      { kind: 'miniPuzzle', targetObjectId: 'door-exit', actionLabel: 'Çıkmadan önce bulmacayı çöz', feedbackLabel: 'Bulmacayı çözdün!', puzzleType: 'loopCount' },
      { kind: 'enterAt', targetObjectId: 'door-exit', actionLabel: 'Evden çık', feedbackLabel: 'Okula gitmeye hazırsın!' },
    ],
    points: 25,
    optimalDurationSeconds: 60,
    minSteps: 4,
  },
];
