import type { HouseNavLevel } from './types';

export const ilkokuluLevels: HouseNavLevel[] = [
  {
    id: 'ilk-1',
    order: 1,
    title: 'Banyoya Git',
    instructions: 'Komutları kullanarak karakteri Banyo kapısına götür.',
    mapRoomId: 'main7',
    startAtObjectId: 'door-child-room',
    taskSteps: [
      { kind: 'moveTo', targetObjectId: 'door-bathroom', actionLabel: 'Banyo kapısına git', feedbackLabel: 'Banyoya ulaştın!' },
    ],
    points: 10,
    optimalDurationSeconds: 45,
    minSteps: 4,
  },
  {
    id: 'ilk-2',
    order: 2,
    title: 'Elini Yüzünü Yıka',
    instructions: 'Lavaboya git ve elini yüzünü yıka. Dikkat, odada seni oyalayacak eşyalar da var!',
    mapRoomId: 'bathroom7',
    taskSteps: [
      { kind: 'enterAt', targetObjectId: 'sink', actionLabel: 'Elini yüzünü yıka', feedbackLabel: 'Elini yüzünü yıkadın!' },
    ],
    points: 15,
    optimalDurationSeconds: 50,
    minSteps: 3,
  },
  {
    id: 'ilk-3',
    order: 3,
    title: 'Mutfağa Git',
    instructions: 'Koridorda bir dolambaç var, dikkatli ilerle. Karakteri Mutfak kapısına götür.',
    mapRoomId: 'main7',
    startAtObjectId: 'door-bathroom',
    taskSteps: [
      { kind: 'moveTo', targetObjectId: 'door-kitchen', actionLabel: 'Mutfak kapısına git', feedbackLabel: 'Mutfağa ulaştın!' },
    ],
    points: 10,
    optimalDurationSeconds: 55,
    minSteps: 5,
  },
  {
    id: 'ilk-4',
    order: 4,
    title: 'Kahvaltı Yap',
    instructions: 'Masanın yanına git, kuralı oku ve duruma göre doğru eylemi seç.',
    mapRoomId: 'kitchen7',
    taskSteps: [
      {
        kind: 'miniPuzzle',
        targetObjectId: 'table',
        actionLabel: 'Beslenme çantanı hazırla',
        feedbackLabel: 'Kahvaltı yaptın!',
        puzzleType: 'conditional',
      },
    ],
    points: 15,
    optimalDurationSeconds: 60,
    minSteps: 2,
  },
  {
    id: 'ilk-5',
    order: 5,
    title: 'Çocuk Odasına Git',
    instructions: 'Komutları kullanarak karakteri Çocuk Odası kapısına götür.',
    mapRoomId: 'main7',
    startAtObjectId: 'door-kitchen',
    taskSteps: [
      { kind: 'moveTo', targetObjectId: 'door-child-room', actionLabel: 'Çocuk Odası kapısına git', feedbackLabel: 'Çocuk odasına ulaştın!' },
    ],
    points: 10,
    optimalDurationSeconds: 45,
    minSteps: 4,
  },
  {
    id: 'ilk-6',
    order: 6,
    title: 'Çantanı Hazırla',
    instructions: 'Önce giyin, sonra masadaki şifreyi çözüp kitabını al, en son çantanı doğru hazırla. Sıra önemli!',
    mapRoomId: 'child-room7',
    taskSteps: [
      {
        kind: 'miniPuzzle',
        targetObjectId: 'wardrobe',
        actionLabel: 'Kıyafetlerini giy',
        feedbackLabel: 'Doğru sırayla giyindin!',
        puzzleType: 'orderedChoice',
      },
      {
        kind: 'miniPuzzle',
        targetObjectId: 'desk',
        actionLabel: 'Çekmecenin şifresini çöz',
        feedbackLabel: 'Kitabı buldun!',
        puzzleType: 'sequence',
      },
      {
        kind: 'miniPuzzle',
        targetObjectId: 'backpack',
        actionLabel: 'Çantanı hazırla',
        feedbackLabel: 'Çantanı doğru hazırladın!',
        puzzleType: 'matching',
      },
    ],
    points: 30,
    optimalDurationSeconds: 150,
    minSteps: 8,
  },
  {
    id: 'ilk-7',
    order: 7,
    title: 'Evden Çık',
    instructions: 'Çıkış kapısına git, önce bulmacayı çöz sonra evden çık.',
    mapRoomId: 'main7',
    startAtObjectId: 'door-child-room',
    taskSteps: [
      { kind: 'miniPuzzle', targetObjectId: 'door-exit', actionLabel: 'Çıkmadan önce bulmacayı çöz', feedbackLabel: 'Bulmacayı çözdün!', puzzleType: 'loopCount' },
      { kind: 'enterAt', targetObjectId: 'door-exit', actionLabel: 'Evden çık', feedbackLabel: 'Okula gitmeye hazırsın!' },
    ],
    points: 25,
    optimalDurationSeconds: 70,
    minSteps: 5,
  },
];
