import type { ConditionalLevel } from '@/types/game';

const GAME_ID = 'conditional-logic-game';

export const conditionalLevels: ConditionalLevel[] = [
  {
    id: 'cond-1',
    gameId: GAME_ID,
    order: 1,
    title: 'Yağmurlu Gün',
    difficulty: 'kolay',
    instructions: 'Duruma göre doğru eylemi seç.',
    points: 10,
    type: 'conditional',
    scenario: 'Eğer dışarıda yağmur yağıyorsa, ne yapmalısın?',
    branches: [
      { id: 'b1', label: 'Şemsiye al', description: 'Yağmurdan korunmak için şemsiye alırsın.' },
      { id: 'b2', label: 'Güneş gözlüğü tak', description: 'Güneşli günlerde işe yarar, ama şimdi değil.' },
    ],
    correctBranchId: 'b1',
  },
  {
    id: 'cond-2',
    gameId: GAME_ID,
    order: 2,
    title: 'Trafik Işığı',
    difficulty: 'kolay',
    instructions: 'Trafik ışığının rengine göre doğru davranışı seç.',
    points: 10,
    type: 'conditional',
    scenario: 'Trafik ışığı kırmızı yandı. Ne yapmalısın?',
    branches: [
      { id: 'b1', label: 'Dur ve bekle', description: 'Kırmızı ışıkta durmak gerekir.' },
      { id: 'b2', label: 'Hızla yürü', description: 'Bu güvenli değil.' },
      { id: 'b3', label: 'Koşarak geç', description: 'Bu çok tehlikeli.' },
    ],
    correctBranchId: 'b1',
  },
  {
    id: 'cond-3',
    gameId: GAME_ID,
    order: 3,
    title: 'Robotun Önündeki Duvar',
    difficulty: 'orta',
    instructions: 'Robotun kuralı: "Eğer önünde duvar varsa dur, yoksa ilerle."',
    points: 15,
    type: 'conditional',
    scenario: 'Robotun tam önünde bir duvar var. Robot ne yapmalı?',
    branches: [
      { id: 'b1', label: 'Dur', description: 'Duvar olduğu için robot ilerleyemez, durmalı.' },
      { id: 'b2', label: 'İlerle', description: 'Bu robotu duvara çarptırır.' },
    ],
    correctBranchId: 'b1',
  },
  {
    id: 'cond-4',
    gameId: GAME_ID,
    order: 4,
    title: 'Sıcak ve Susamış',
    difficulty: 'orta',
    instructions: 'İki koşulu birlikte değerlendir: "Eğer hava sıcaksa VE susadıysan..."',
    points: 15,
    type: 'conditional',
    scenario: 'Hava çok sıcak ve çok susadın. Ne yapmalısın?',
    branches: [
      { id: 'b1', label: 'Su iç', description: 'Sıcak ve susamış olduğun için su içmelisin.' },
      { id: 'b2', label: 'Kalın kazak giy', description: 'Bu sıcak havada mantıklı değil.' },
      { id: 'b3', label: 'Uyumaya git', description: 'Susuzluğunu gidermez.' },
    ],
    correctBranchId: 'b1',
  },
  {
    id: 'cond-5',
    gameId: GAME_ID,
    order: 5,
    title: 'Akşam Oldu',
    difficulty: 'zor',
    instructions: 'Üç farklı durumdan doğru olanı seç.',
    points: 20,
    type: 'conditional',
    scenario: 'Saat akşam oldu, hava karardı ve çok yorgunsun. Şimdi ne yapmalısın?',
    branches: [
      { id: 'b1', label: 'Uyumaya hazırlan', description: 'Akşam oldu ve yorgunsun, uyku vakti geldi.' },
      { id: 'b2', label: 'Dışarı oyuna çık', description: 'Hava karanlık, dışarı çıkmak için uygun değil.' },
      { id: 'b3', label: 'Öğle yemeği ye', description: 'Öğle yemeği vakti çoktan geçti.' },
    ],
    correctBranchId: 'b1',
  },
];
