import type { FlowchartLevel } from '@/types/game';

// Metadata shells only — scenario/availableBlocks/correctSequence below are placeholders required by
// the FlowchartLevel type but never actually shown to players. FlowLogicGamePlayer regenerates all
// three fresh from scenarioPool.ts every time a level is entered (see generator.ts). Only id, order,
// title, difficulty, instructions, points, optimalDurationSeconds and minSteps are real here.
const GAME_ID = 'flow-logic-game';

export const flowLogicLevels: FlowchartLevel[] = [
  {
    id: 'flow-1',
    gameId: GAME_ID,
    order: 1,
    title: 'Kırmızı Engelden Zıpla',
    difficulty: 'kolay',
    instructions: 'Sadece gerekli blokları doğru sırayla seç. Gereksiz bloklara dokunma!',
    points: 10,
    optimalDurationSeconds: 40,
    minSteps: 2,
    type: 'flowchart',
    scenario: 'Karakterin önünde kırmızı bir engel var. Kural: Eğer engel kırmızıysa zıpla, değilse yürü.',
    availableBlocks: [
      { id: 'cond-red', label: 'Eğer engel kırmızıysa', kind: 'condition' },
      { id: 'cond-blue', label: 'Eğer engel maviyse', kind: 'condition' },
      { id: 'act-jump', label: 'Zıpla', kind: 'action' },
      { id: 'act-duck', label: 'Eğil', kind: 'action' },
    ],
    correctSequence: ['cond-red', 'act-jump'],
  },
  {
    id: 'flow-2',
    gameId: GAME_ID,
    order: 2,
    title: 'Yeşil Işıkta Yürü',
    difficulty: 'kolay',
    instructions: 'Sadece gerekli blokları doğru sırayla seç.',
    points: 10,
    optimalDurationSeconds: 40,
    minSteps: 2,
    type: 'flowchart',
    scenario: 'Trafik ışığı yeşil yandı. Kural: Eğer ışık yeşilse yürü, kırmızıysa dur.',
    availableBlocks: [
      { id: 'cond-green', label: 'Eğer ışık yeşilse', kind: 'condition' },
      { id: 'cond-red-light', label: 'Eğer ışık kırmızıysa', kind: 'condition' },
      { id: 'act-walk', label: 'Yürü', kind: 'action' },
      { id: 'act-stop', label: 'Dur', kind: 'action' },
    ],
    correctSequence: ['cond-green', 'act-walk'],
  },
  {
    id: 'flow-3',
    gameId: GAME_ID,
    order: 3,
    title: '3 Kez Zıpla',
    difficulty: 'orta',
    instructions: 'Bu sefer bir de tekrar (döngü) bloğu var. Doğru koşul + döngü + eylemi sırayla seç.',
    points: 15,
    optimalDurationSeconds: 60,
    minSteps: 3,
    type: 'flowchart',
    scenario: 'Önünde 3 tane küçük engel var. Kural: Eğer engel varsa, 3 kez zıpla.',
    availableBlocks: [
      { id: 'cond-obstacle', label: 'Eğer engel varsa', kind: 'condition' },
      { id: 'loop-3', label: '3 Kez Tekrarla', kind: 'loop' },
      { id: 'loop-5', label: '5 Kez Tekrarla', kind: 'loop' },
      { id: 'act-jump', label: 'Zıpla', kind: 'action' },
      { id: 'act-walk', label: 'Yürü', kind: 'action' },
    ],
    correctSequence: ['cond-obstacle', 'loop-3', 'act-jump'],
  },
  {
    id: 'flow-4',
    gameId: GAME_ID,
    order: 4,
    title: 'Soğuk mu Sıcak mı',
    difficulty: 'orta',
    instructions: 'Sadece gerekli blokları doğru sırayla seç.',
    points: 15,
    optimalDurationSeconds: 55,
    minSteps: 2,
    type: 'flowchart',
    scenario: 'Hava çok soğuk. Kural: Eğer hava soğuksa mont giy, değilse tişört giy.',
    availableBlocks: [
      { id: 'cond-cold', label: 'Eğer hava soğuksa', kind: 'condition' },
      { id: 'cond-hot', label: 'Eğer hava sıcaksa', kind: 'condition' },
      { id: 'act-coat', label: 'Mont giy', kind: 'action' },
      { id: 'act-tshirt', label: 'Tişört giy', kind: 'action' },
    ],
    correctSequence: ['cond-cold', 'act-coat'],
  },
  {
    id: 'flow-5',
    gameId: GAME_ID,
    order: 5,
    title: 'Yağmur ve Su Birikintileri',
    difficulty: 'zor',
    instructions: 'Bu seviyede koşul, eylem ve döngü birlikte kullanılıyor. Dikkatli seç!',
    points: 20,
    optimalDurationSeconds: 90,
    minSteps: 4,
    type: 'flowchart',
    scenario:
      'Yağmur yağıyor ve yolda 4 tane su birikintisi var. Kural: Eğer yağmur yağıyorsa şemsiyeni aç, sonra 4 kez su birikintisinin üzerinden atla.',
    availableBlocks: [
      { id: 'cond-rain', label: 'Eğer yağmur yağıyorsa', kind: 'condition' },
      { id: 'cond-sunny', label: 'Eğer güneşliyse', kind: 'condition' },
      { id: 'act-umbrella', label: 'Şemsiyeni aç', kind: 'action' },
      { id: 'act-sunglasses', label: 'Güneş gözlüğü tak', kind: 'action' },
      { id: 'loop-4', label: '4 Kez Tekrarla', kind: 'loop' },
      { id: 'loop-2', label: '2 Kez Tekrarla', kind: 'loop' },
      { id: 'act-jumppuddle', label: 'Su birikintisinin üzerinden atla', kind: 'action' },
    ],
    correctSequence: ['cond-rain', 'act-umbrella', 'loop-4', 'act-jumppuddle'],
  },
];
