import type { FlowchartLevel } from '@/types/game';

// Metadata shells only — scenario/variables/actionOptions/operatorOptions/expectedSteps/resultTemplate
// below are empty placeholders required by the FlowchartLevel type but never actually shown to
// players. FlowLogicGamePlayer regenerates all of them fresh from templates.ts every time a level is
// entered (see generator.ts). Only id, order, title, difficulty, instructions, points,
// optimalDurationSeconds and minSteps are real here.
const GAME_ID = 'flow-logic-game';

export const flowLogicLevels: FlowchartLevel[] = [
  {
    id: 'flow-1',
    gameId: GAME_ID,
    order: 1,
    title: 'Tek Koşullu Akış',
    difficulty: 'kolay',
    instructions: 'Bir "Eğer" bloğu ve bir "Eylem" bloğu kur, sonuna "Sonucu Hesapla" bloğunu ekle.',
    points: 10,
    optimalDurationSeconds: 60,
    minSteps: 3,
    type: 'flowchart',
    scenario: '',
    variables: [],
    actionOptions: [],
    operatorOptions: [],
    expectedSteps: [],
    resultTemplate: '',
  },
  {
    id: 'flow-2',
    gameId: GAME_ID,
    order: 2,
    title: 'Döngülü Akış',
    difficulty: 'kolay',
    instructions: 'Bir "Tekrarla" bloğu ve bir "Eylem" bloğu kur, sayacı doğru ayarla.',
    points: 10,
    optimalDurationSeconds: 60,
    minSteps: 3,
    type: 'flowchart',
    scenario: '',
    variables: [],
    actionOptions: [],
    operatorOptions: [],
    expectedSteps: [],
    resultTemplate: '',
  },
  {
    id: 'flow-3',
    gameId: GAME_ID,
    order: 3,
    title: 'Koşul ve Döngü Birlikte',
    difficulty: 'orta',
    instructions: 'Önce "Eğer" ile koşulu kur, sonra "Tekrarla" ile döngüyü, en son eylemi ve sonucu ekle.',
    points: 15,
    optimalDurationSeconds: 90,
    minSteps: 4,
    type: 'flowchart',
    scenario: '',
    variables: [],
    actionOptions: [],
    operatorOptions: [],
    expectedSteps: [],
    resultTemplate: '',
  },
  {
    id: 'flow-4',
    gameId: GAME_ID,
    order: 4,
    title: 'Daha Fazla Karşılaştırma',
    difficulty: 'orta',
    instructions: 'Bu sefer büyüktür-eşittir gibi farklı karşılaştırmalar da var. Değişkeni ve karşılaştırmayı dikkatli seç.',
    points: 15,
    optimalDurationSeconds: 100,
    minSteps: 4,
    type: 'flowchart',
    scenario: '',
    variables: [],
    actionOptions: [],
    operatorOptions: [],
    expectedSteps: [],
    resultTemplate: '',
  },
  {
    id: 'flow-5',
    gameId: GAME_ID,
    order: 5,
    title: 'İki Aşamalı Akış',
    difficulty: 'zor',
    instructions: 'Bu seviyede iki ayrı kural var. Her ikisini de doğru sırayla, doğru şekilde kurmalısın.',
    points: 20,
    optimalDurationSeconds: 150,
    minSteps: 6,
    type: 'flowchart',
    scenario: '',
    variables: [],
    actionOptions: [],
    operatorOptions: [],
    expectedSteps: [],
    resultTemplate: '',
  },
];
