import type { DebugLevel } from '@/types/game';

const GAME_ID = 'debug-hunt-game';

export const debugLevels: DebugLevel[] = [
  {
    id: 'dbg-1',
    gameId: GAME_ID,
    order: 1,
    title: 'Elleri Yıkama',
    difficulty: 'kolay',
    instructions: 'Bu adım listesinde sırası yanlış olan adımı bul.',
    points: 10,
    type: 'debug',
    steps: [
      { id: 'st1', label: 'Musluğu aç' },
      { id: 'st2', label: 'Elleri sabunla' },
      { id: 'st3', label: 'Havluyla kurula' },
      { id: 'st4', label: 'Elleri suyla durula' },
    ],
    buggyStepId: 'st3',
    explanation: '"Havluyla kurula" adımı, eller durulanmadan önce yapılamaz. Bu adım "elleri suyla durula" adımından sonra gelmeli.',
  },
  {
    id: 'dbg-2',
    gameId: GAME_ID,
    order: 2,
    title: 'Robotun Düz Yolu',
    difficulty: 'kolay',
    instructions: 'Robot düz bir yolda ilerlemeli. Fazladan olan yanlış komutu bul.',
    points: 10,
    type: 'debug',
    steps: [
      { id: 'st1', label: '1 adım ileri git' },
      { id: 'st2', label: '1 adım ileri git' },
      { id: 'st3', label: 'Sağa dön' },
      { id: 'st4', label: '1 adım ileri git' },
    ],
    buggyStepId: 'st3',
    explanation: 'Yol düz olduğu için robotun dönmesine gerek yok. "Sağa dön" komutu robotu yoldan çıkarır.',
  },
  {
    id: 'dbg-3',
    gameId: GAME_ID,
    order: 3,
    title: 'Meyve Suyu Tarifi',
    difficulty: 'orta',
    instructions: 'Tarifte doğru malzemeyle uyuşmayan adımı bul.',
    points: 15,
    type: 'debug',
    steps: [
      { id: 'st1', label: 'Portakalları yıka' },
      { id: 'st2', label: 'Portakalları sık' },
      { id: 'st3', label: 'Tuz ekle' },
      { id: 'st4', label: 'Bardağa koy ve iç' },
    ],
    buggyStepId: 'st3',
    explanation: 'Meyve suyuna tuz eklenmez. Bu adım yanlış; "isteğe bağlı şeker ekle" olmalıydı.',
  },
  {
    id: 'dbg-4',
    gameId: GAME_ID,
    order: 4,
    title: 'Labirentte Kayıp Robot',
    difficulty: 'orta',
    instructions: 'Robot hedefe ulaşamadı. Onu yoldan çıkaran hatalı yön komutunu bul.',
    points: 15,
    type: 'debug',
    steps: [
      { id: 'st1', label: '2 adım ileri git' },
      { id: 'st2', label: 'Sağa dön' },
      { id: 'st3', label: '1 adım ileri git' },
      { id: 'st4', label: 'Sağa dön' },
      { id: 'st5', label: '2 adım ileri git' },
    ],
    buggyStepId: 'st4',
    explanation: 'İkinci "sağa dön" komutu robotu hedefin tam tersi yöne çevirir; burada "sola dön" olmalıydı.',
  },
  {
    id: 'dbg-5',
    gameId: GAME_ID,
    order: 5,
    title: 'Bahçe Sulama Rutini',
    difficulty: 'zor',
    instructions: 'Bu uzun listede hedefe ulaşmayı engelleyen adımı bul.',
    points: 20,
    type: 'debug',
    steps: [
      { id: 'st1', label: 'Sulama kabını doldur' },
      { id: 'st2', label: 'Çiçeklere git' },
      { id: 'st3', label: 'Kabı ters çevirip boşalt' },
      { id: 'st4', label: 'Çiçekleri sula' },
      { id: 'st5', label: 'Kabı yerine koy' },
      { id: 'st6', label: 'Elleri yıka' },
    ],
    buggyStepId: 'st3',
    explanation: 'Kap çiçeklere ulaşmadan boşaltılırsa çiçekler sulanamaz. Bu adım "çiçekleri sula" adımından sonra gelmeli.',
  },
];
