import type { SequencingLevel } from '@/types/game';

const GAME_ID = 'sequencing-game';

export const sequencingLevels: SequencingLevel[] = [
  {
    id: 'seq-1',
    gameId: GAME_ID,
    order: 1,
    title: 'Diş Fırçalama Zamanı',
    difficulty: 'kolay',
    instructions: 'Diş fırçalama rutinini doğru sıraya diz.',
    points: 10,
    optimalDurationSeconds: 40,
    minSteps: 5,
    type: 'sequencing',
    items: [
      { id: 'a', label: 'Ellerini yıka' },
      { id: 'b', label: 'Diş fırçasına macun sür' },
      { id: 'c', label: 'Dişlerini fırçala' },
      { id: 'd', label: 'Ağzını suyla çalkala' },
      { id: 'e', label: 'Fırçanı yıka ve yerine koy' },
    ],
    correctOrder: ['a', 'b', 'c', 'd', 'e'],
  },
  {
    id: 'seq-2',
    gameId: GAME_ID,
    order: 2,
    title: 'Okula Hazırlanıyorum',
    difficulty: 'kolay',
    instructions: 'Sabah okula hazırlanma adımlarını doğru sıraya diz.',
    points: 10,
    optimalDurationSeconds: 50,
    minSteps: 6,
    type: 'sequencing',
    items: [
      { id: 'a', label: 'Uyan ve yatağını topla' },
      { id: 'b', label: 'Kahvaltı yap' },
      { id: 'c', label: 'Kıyafetlerini giy' },
      { id: 'd', label: 'Ayakkabılarını giy' },
      { id: 'e', label: 'Çantanı hazırla' },
      { id: 'f', label: 'Evden çık' },
    ],
    correctOrder: ['a', 'b', 'c', 'd', 'e', 'f'],
  },
  {
    id: 'seq-3',
    gameId: GAME_ID,
    order: 3,
    title: 'Sandviç Ustası',
    difficulty: 'orta',
    instructions: 'Lezzetli bir sandviç hazırlamak için adımları doğru sıraya diz.',
    points: 15,
    optimalDurationSeconds: 65,
    minSteps: 7,
    type: 'sequencing',
    items: [
      { id: 'a', label: 'Ellerini yıka' },
      { id: 'b', label: 'İki dilim ekmek al' },
      { id: 'c', label: 'Ekmeklere tereyağı sür' },
      { id: 'd', label: 'Peynir ve domates yerleştir' },
      { id: 'e', label: 'Ekmekleri üst üste kapat' },
      { id: 'f', label: 'Sandviçi ikiye kes' },
      { id: 'g', label: 'Tabağa koy ve servis yap' },
    ],
    correctOrder: ['a', 'b', 'c', 'd', 'e', 'f', 'g'],
  },
  {
    id: 'seq-4',
    gameId: GAME_ID,
    order: 4,
    title: 'Küçük Bahçıvan',
    difficulty: 'orta',
    instructions: 'Bir tohumu dikip yetiştirme adımlarını doğru sıraya diz.',
    points: 15,
    optimalDurationSeconds: 75,
    minSteps: 8,
    type: 'sequencing',
    items: [
      { id: 'a', label: 'Saksıyı seç' },
      { id: 'b', label: 'Saksıya toprak koy' },
      { id: 'c', label: 'Toprağa küçük bir çukur aç' },
      { id: 'd', label: 'Tohumu çukura bırak' },
      { id: 'e', label: 'Üzerini toprakla kapat' },
      { id: 'f', label: 'Su ver' },
      { id: 'g', label: 'Güneşli bir yere koy' },
      { id: 'h', label: 'Her gün kontrol edip bekle' },
    ],
    correctOrder: ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h'],
  },
  {
    id: 'seq-5',
    gameId: GAME_ID,
    order: 5,
    title: 'Robotu Yönlendir',
    difficulty: 'zor',
    instructions: 'Robotun haritada A noktasından B noktasına gitmesi için komutları doğru sıraya diz.',
    points: 20,
    optimalDurationSeconds: 90,
    minSteps: 8,
    type: 'sequencing',
    items: [
      { id: 'a', label: '3 adım ileri git' },
      { id: 'b', label: 'Sağa dön' },
      { id: 'c', label: '2 adım ileri git' },
      { id: 'd', label: 'Sola dön' },
      { id: 'e', label: '1 adım ileri git' },
      { id: 'f', label: 'Sağa dön' },
      { id: 'g', label: '2 adım ileri git' },
      { id: 'h', label: 'Hedefe ulaştın, dur' },
    ],
    correctOrder: ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h'],
  },
  {
    id: 'seq-6',
    gameId: GAME_ID,
    order: 6,
    title: 'Büyük Doğum Günü Partisi',
    difficulty: 'zor',
    instructions: 'Doğum günü partisi hazırlıklarının hepsini doğru sıraya diz — bu sefer çok daha uzun!',
    points: 25,
    optimalDurationSeconds: 150,
    minSteps: 12,
    type: 'sequencing',
    items: [
      { id: 'a', label: 'Davetiyeleri hazırla' },
      { id: 'b', label: 'Davetiyeleri dağıt' },
      { id: 'c', label: 'Salonu süsle' },
      { id: 'd', label: 'Balonları şişir' },
      { id: 'e', label: 'Pastayı fırından çıkar' },
      { id: 'f', label: 'Pastayı süsle' },
      { id: 'g', label: 'Masayı kur' },
      { id: 'h', label: 'İkramları masaya diz' },
      { id: 'i', label: 'Müzik çal' },
      { id: 'j', label: 'Misafirleri karşıla' },
      { id: 'k', label: 'Oyunları başlat' },
      { id: 'l', label: 'Pastayı kesip mumları üfle' },
    ],
    correctOrder: ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l'],
  },
];
