import type { SequencingLevel } from '@/types/game';

const GAME_ID = 'sequencing-game';

export const sequencingLevels: SequencingLevel[] = [
  {
    id: 'seq-1',
    gameId: GAME_ID,
    order: 1,
    title: 'Diş Fırçalama Zamanı',
    difficulty: 'kolay',
    instructions: 'Diş fırçalama rutinini doğru sıraya diz.',
    points: 10,
    type: 'sequencing',
    items: [
      { id: 'a', label: 'Diş fırçasına macun sür' },
      { id: 'b', label: 'Dişlerini fırçala' },
      { id: 'c', label: 'Ağzını suyla çalkala' },
      { id: 'd', label: 'Fırçanı yıka ve yerine koy' },
    ],
    correctOrder: ['a', 'b', 'c', 'd'],
  },
  {
    id: 'seq-2',
    gameId: GAME_ID,
    order: 2,
    title: 'Okula Hazırlanıyorum',
    difficulty: 'kolay',
    instructions: 'Sabah okula hazırlanma adımlarını doğru sıraya diz.',
    points: 10,
    type: 'sequencing',
    items: [
      { id: 'a', label: 'Uyan ve yatağını topla' },
      { id: 'b', label: 'Kahvaltı yap' },
      { id: 'c', label: 'Kıyafetlerini giy' },
      { id: 'd', label: 'Çantanı hazırla' },
      { id: 'e', label: 'Evden çık' },
    ],
    correctOrder: ['a', 'b', 'c', 'd', 'e'],
  },
  {
    id: 'seq-3',
    gameId: GAME_ID,
    order: 3,
    title: 'Sandviç Ustası',
    difficulty: 'orta',
    instructions: 'Lezzetli bir sandviç hazırlamak için adımları doğru sıraya diz.',
    points: 15,
    type: 'sequencing',
    items: [
      { id: 'a', label: 'İki dilim ekmek al' },
      { id: 'b', label: 'Ekmeklere tereyağı sür' },
      { id: 'c', label: 'Peynir ve domates yerleştir' },
      { id: 'd', label: 'Ekmekleri üst üste kapat' },
      { id: 'e', label: 'Sandviçi ikiye kes ve tabağa koy' },
    ],
    correctOrder: ['a', 'b', 'c', 'd', 'e'],
  },
  {
    id: 'seq-4',
    gameId: GAME_ID,
    order: 4,
    title: 'Küçük Bahçıvan',
    difficulty: 'orta',
    instructions: 'Bir tohumu dikip yetiştirme adımlarını doğru sıraya diz.',
    points: 15,
    type: 'sequencing',
    items: [
      { id: 'a', label: 'Saksıya toprak koy' },
      { id: 'b', label: 'Toprağa küçük bir çukur aç' },
      { id: 'c', label: 'Tohumu çukura bırak' },
      { id: 'd', label: 'Üzerini toprakla kapat' },
      { id: 'e', label: 'Su ver' },
      { id: 'f', label: 'Güneşli bir yere koy ve bekle' },
    ],
    correctOrder: ['a', 'b', 'c', 'd', 'e', 'f'],
  },
  {
    id: 'seq-5',
    gameId: GAME_ID,
    order: 5,
    title: 'Robotu Yönlendir',
    difficulty: 'zor',
    instructions: 'Robotun haritada A noktasından B noktasına gitmesi için komutları doğru sıraya diz.',
    points: 20,
    type: 'sequencing',
    items: [
      { id: 'a', label: '3 adım ileri git' },
      { id: 'b', label: 'Sağa dön' },
      { id: 'c', label: '2 adım ileri git' },
      { id: 'd', label: 'Sola dön' },
      { id: 'e', label: '1 adım ileri git' },
      { id: 'f', label: 'Hedefe ulaştın, dur' },
    ],
    correctOrder: ['a', 'b', 'c', 'd', 'e', 'f'],
  },
];
