import type { PatternLevel } from '@/types/game';

const GAME_ID = 'pattern-completion-game';

export const patternLevels: PatternLevel[] = [
  {
    id: 'pat-1',
    gameId: GAME_ID,
    order: 1,
    title: 'Renk Dizisi',
    difficulty: 'kolay',
    instructions: 'Örüntüde eksik olan rengi bul.',
    points: 10,
    type: 'pattern',
    sequence: [
      { id: 's1', kind: 'color', value: 'bg-rose-400', label: 'kırmızı' },
      { id: 's2', kind: 'color', value: 'bg-blue-400', label: 'mavi' },
      { id: 's3', kind: 'color', value: 'bg-rose-400', label: 'kırmızı' },
      { id: 's4', kind: 'color', value: 'bg-blue-400', label: 'mavi' },
      { id: 's5', kind: 'color', value: '', label: '?' },
    ],
    missingIndex: 4,
    options: [
      { id: 'opt-a', kind: 'color', value: 'bg-rose-400', label: 'kırmızı' },
      { id: 'opt-b', kind: 'color', value: 'bg-blue-400', label: 'mavi' },
      { id: 'opt-c', kind: 'color', value: 'bg-emerald-400', label: 'yeşil' },
    ],
    correctOptionId: 'opt-a',
  },
  {
    id: 'pat-2',
    gameId: GAME_ID,
    order: 2,
    title: 'Şekil Dizisi',
    difficulty: 'kolay',
    instructions: 'Örüntüde eksik olan şekli bul.',
    points: 10,
    type: 'pattern',
    sequence: [
      { id: 's1', kind: 'shape', value: 'circle', label: 'daire' },
      { id: 's2', kind: 'shape', value: 'square', label: 'kare' },
      { id: 's3', kind: 'shape', value: 'triangle', label: 'üçgen' },
      { id: 's4', kind: 'shape', value: 'circle', label: 'daire' },
      { id: 's5', kind: 'shape', value: 'square', label: 'kare' },
      { id: 's6', kind: 'shape', value: '', label: '?' },
    ],
    missingIndex: 5,
    options: [
      { id: 'opt-a', kind: 'shape', value: 'triangle', label: 'üçgen' },
      { id: 'opt-b', kind: 'shape', value: 'circle', label: 'daire' },
      { id: 'opt-c', kind: 'shape', value: 'square', label: 'kare' },
    ],
    correctOptionId: 'opt-a',
  },
  {
    id: 'pat-3',
    gameId: GAME_ID,
    order: 3,
    title: 'Büyüyen Yıldızlar',
    difficulty: 'orta',
    instructions: 'Her adımda bir yıldız artıyor. Eksik olanı bul.',
    points: 15,
    type: 'pattern',
    sequence: [
      { id: 's1', kind: 'icon', value: '★', label: '1 yıldız' },
      { id: 's2', kind: 'icon', value: '★★', label: '2 yıldız' },
      { id: 's3', kind: 'icon', value: '★★★', label: '3 yıldız' },
      { id: 's4', kind: 'icon', value: '', label: '?' },
    ],
    missingIndex: 3,
    options: [
      { id: 'opt-a', kind: 'icon', value: '★★★★', label: '4 yıldız' },
      { id: 'opt-b', kind: 'icon', value: '★★', label: '2 yıldız' },
      { id: 'opt-c', kind: 'icon', value: '★★★★★', label: '5 yıldız' },
    ],
    correctOptionId: 'opt-a',
  },
  {
    id: 'pat-4',
    gameId: GAME_ID,
    order: 4,
    title: 'Renk ve Şekil Birlikte',
    difficulty: 'orta',
    instructions: 'Bu örüntüde hem renk hem şekil birlikte değişiyor. Eksiği bul.',
    points: 15,
    type: 'pattern',
    sequence: [
      { id: 's1', kind: 'icon', value: 'red:circle', label: 'kırmızı daire' },
      { id: 's2', kind: 'icon', value: 'blue:square', label: 'mavi kare' },
      { id: 's3', kind: 'icon', value: 'red:circle', label: 'kırmızı daire' },
      { id: 's4', kind: 'icon', value: 'blue:square', label: 'mavi kare' },
      { id: 's5', kind: 'icon', value: '', label: '?' },
    ],
    missingIndex: 4,
    options: [
      { id: 'opt-a', kind: 'icon', value: 'red:circle', label: 'kırmızı daire' },
      { id: 'opt-b', kind: 'icon', value: 'blue:circle', label: 'mavi daire' },
      { id: 'opt-c', kind: 'icon', value: 'red:square', label: 'kırmızı kare' },
    ],
    correctOptionId: 'opt-a',
  },
  {
    id: 'pat-5',
    gameId: GAME_ID,
    order: 5,
    title: 'Ayna Örüntüsü',
    difficulty: 'zor',
    instructions: 'Bu örüntü bir ayna gibi simetrik. Eksik olan şekli bul.',
    points: 20,
    type: 'pattern',
    sequence: [
      { id: 's1', kind: 'shape', value: 'circle', label: 'daire' },
      { id: 's2', kind: 'shape', value: 'square', label: 'kare' },
      { id: 's3', kind: 'shape', value: 'triangle', label: 'üçgen' },
      { id: 's4', kind: 'shape', value: 'triangle', label: 'üçgen' },
      { id: 's5', kind: 'shape', value: 'square', label: 'kare' },
      { id: 's6', kind: 'shape', value: '', label: '?' },
    ],
    missingIndex: 5,
    options: [
      { id: 'opt-a', kind: 'shape', value: 'circle', label: 'daire' },
      { id: 'opt-b', kind: 'shape', value: 'triangle', label: 'üçgen' },
      { id: 'opt-c', kind: 'shape', value: 'square', label: 'kare' },
    ],
    correctOptionId: 'opt-a',
  },
];
